import type { Metadata } from "next";
import "@/styles/globals.css";
import vazirFont from "@/constants/local-font";
import Header from "@/components/shared/header/header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl" className={vazirFont.variable}>
            <body className={vazirFont.variable}>
                <Header />
                {children}
            </body>
        </html>
    );
}
